version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"  
      - "15672:15672"  
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  app:
    build: .
    container_name: my-node-app
    restart: always
    depends_on:
      - rabbitmq
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - RABBITMQ_URL=amqp://rabbitmq
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: ["npm", "run", "dev"]
