version: '3.8'

networks:
  bhut-network:  # Definição da rede

services:
  app:
    build: .
    container_name: bhut-backend_app
    ports:
      - "3000:3000"  # Porta da aplicação
      - "9229:9229"  # Porta de depuração
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - MONGO_URI=mongodb://mongo:27017/bhut
    depends_on:
      - rabbitmq
      - mongo
    entrypoint: ["sh", "-c", "sleep 10 && npm start"]
    networks:
      - bhut-network  # Conectando à rede

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - bhut-network  # Conectando à rede

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - bhut-network  # Conectando à rede

volumes:
  mongo-data:
