version: '3.8'

services:
  app:
    build: .
    container_name: bhut-backend_app
    ports:
      - "3000:3000"  
      - "9229:9229"  
    env_file:
      - .env  
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - MONGO_URI=mongodb://mongo:27017/bhut
      - WEBHOOK=https://webhook.site/seu_web_hook
      - BASEURL=https://sua_api.exemplo.com
      - USUARIO=seu_usuario
      - SENHA=sua_senha
    depends_on:
      - rabbitmq
      - mongo
    entrypoint: ["sh", "-c", "dockerize -wait tcp://rabbitmq:5672 -wait tcp://mongo:27017 -timeout 30s npm run build && npm start"]
    
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
